# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development: &default
  secret_key_base:        8dbad6cd5c126e4240c4832522403456e918135792795996e463df03a6e47c72d89fe83ece0b443769d31e85624c74e8509e4fb0ee3093f916fee86717898388
  redis_url_cache:        redis://redis:6379/0
  redis_url_app:          redis://redis:6379/1
  redis_url_sidekiq:      redis://redis:6379/2
  sidekiq_username:
  sidekiq_password:
  mysql_database:         ir_investidor_development
  mysql_host:             db
  mysql_port:             3316
  mysql_username:         root
  mysql_password:
  mysql_pool:             5
  mysql_idle_timeout:     300
  mysql_checkout_timeout: 5

test:
  <<: *default
  secret_key_base:        5bf4442fdbf8168ca8c044a71b6a2cd3a5f4ec04efb77f285c0248da6e40b0373003659ac71202afc6461f04d7c25ae2fd23473e70b06ae0b0823ccaa5947e94
  mysql_database:         ir_investidor_test

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base:        <%= ENV['SECRET_KEY_BASE'] %>
  redis_url_cache:        <%= ENV['REDIS_URL'] %>/0
  redis_url_app:          <%= ENV['REDIS_URL'] %>/1
  redis_url_sidekiq:      <%= ENV['REDIS_URL'] %>/2
  sidekiq_username:       <%= ENV['SIDEKIQ_USERNAME'] %>
  sidekiq_password:       <%= ENV['SIDEKIQ_PASSWORD'] %>
  mysql_database:         <%= ENV['MYSQL_DATABASE'] %>
  mysql_host:             <%= ENV['MYSQL_HOST'] %>
  mysql_port:             <%= ENV['MYSQL_PORT'] %>
  mysql_username:         <%= ENV['MYSQL_USERNAME'] %>
  mysql_password:         <%= ENV['MYSQL_PASSWORD'] %>
  mysql_pool:             <%= ENV.fetch("MYSQL_POOL") { 5 }.to_i %>
  mysql_idle_timeout:     <%= ENV.fetch("MYSQL_IDLE_TIMEOUT") { 300 }.to_i %>
  mysql_checkout_timeout: <%= ENV.fetch("MYSQL_CHECKOUT_TIMEOUT") { 5 }.to_i %>
